spring.application.name=SpringBoot_MidTerm

# Server Port Rule
server.port=3001

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/Ecom-SpringBoot-SV26
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Thymeleaf Cache (disable for development)
spring.thymeleaf.cache=false

